name: milk
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  form_field_validator: ^1.0.1
  cloud_firestore: ^0.14.4
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.7
  http: ^0.11.3+17
  progress_dialog: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Gloria
      fonts:
        - asset: fonts/GloriaHallelujah-Regular.ttf
    - family: Langer
      fonts:
        - asset: fonts/Langar-Regular.ttf
    - family: Russo
      fonts:
        - asset: fonts/RussoOne-Regular.ttf
    - family: Alfa
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf

  assets:
    - images/


